### ISSUE TITLE
Ignore workspace packages for restrict-ranges rule

### ISSUE THREAD

**Issue by joshferrell** [kellyselden/eslint-plugin-json-files#144]
Given the following configuration:
```
{
  files: ['package.json'],
  plugins: ['json-files'],
  extends: [],
  rules: {
    "json-files/sort-package-json": "error",
    "json-files/restrict-ranges": [1, { versionHint: "pin" }]
  }
}
```

I currently get errors when the package is something like:

```
// package.json
{
  "devDependencies": {
    "tsconfig": "workspace:*"
  }
}
```

Since the project is a monorepo, packages should come from the local workspace and pinning is not necessary. Therfore, I'd like to be able to add exceptions for `"workspace:*"` or exceptions for specific packages like `tsconfig` in this case.

**Comment by kellyselden** [comment]
This should be possible with the "packages" option https://github.com/kellyselden/eslint-plugin-json-files/blob/master/docs/rules/restrict-ranges.md#options.

**Comment by joshferrell** [comment]
Didn't see that option, thanks. For anyone who comes from google and is curious how to make this work:

```
// package.json
{
  "devDependencies": {
    "tsconfig": "workspace:*",
    "react": "^1.2.3",
    "react-dom": "1.2.3"
  }
}
```

```
{
  files: ['package.json'],
  plugins: ['json-files'],
  extends: [],
  rules: {
    "json-files/restrict-ranges": [2, [{ versionRegex: 'workspace:*', packages: ['tsconfig'] }, { versionHint: "pin" }]] 
   }
}
```

This makes all packages in the first array (tsconfig) have to have a package version of `workspace:*` and all other packages that don't match must be pinned.
