### ISSUE TITLE
Sorting of package.json not respecting indentation

### ISSUE THREAD

**Issue by brentonhouse** [kellyselden/eslint-plugin-json-files#30]
The `sort-package-json` package sorts package.json by checking the indentation used in the file but it seems like this plugin is overriding it by applying an indentation of 2 spaces.

**Comment by kellyselden** [comment]
Good catch! I think I see the problem.

**Comment by kellyselden** [comment]
This should be fixed in v0.8.0. Can you try it out?

**Comment by brentonhouse** [comment]
Works!!  Thanks for the very quick fix!!
